Main svc
AlexanderKolnakov/java-explore-with-me pull request #4
Opened 2023-04-24 14:11 UTC by AlexanderKolnakov

2023-05-01 23:54 UTC, AlexanderKolnakov commented
Есть моменты где просится рефакторинг, постараюсь сделать к финальной части проекта.

2023-05-02 00:06 UTC, AlexanderKolnakov commented
Проект собран для работы в контейнере. Для локальной работы необходимо в классе StatsClient модуля stats-client поменять значения ("http://stats-server:9090") String serverUrl в конструкторе класса на ("http://localhost:9090") String serverUrl. Ну и подключить соответствующие БД. 
Но наверное и эти моменты можно сразу настроить

2023-05-03 02:30 UTC, EvgenyKoptubenko commented
Если отправить такой запрос, то приходит странный ответ
curl --request POST \
  --url http://localhost:8080/admin/users \
  --header 'Content-Type: application/json' \
  --data '{
	"name":"namessssItem",
	"email":"email3email.com",
  "login":"login",
	"birthday":"2012-04-23T18:25:43.511Z"
}'

{
	"cause": null,
	"stackTrace": [
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "error400",
			"fileName": "ErrorHandler.java",
			"lineNumber": 26,
			"className": "ru.practicum.ewm.exception.ErrorHandler",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": "java.base",
			"moduleVersion": "11.0.19",
			"methodName": "invoke0",
			"fileName": "NativeMethodAccessorImpl.java",
			"lineNumber": -2,
			"className": "jdk.internal.reflect.NativeMethodAccessorImpl",
			"nativeMethod": true
		},
		{
			"classLoaderName": null,
			"moduleName": "java.base",
			"moduleVersion": "11.0.19",
			"methodName": "invoke",
			"fileName": "NativeMethodAccessorImpl.java",
			"lineNumber": 62,
			"className": "jdk.internal.reflect.NativeMethodAccessorImpl",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": "java.base",
			"moduleVersion": "11.0.19",
			"methodName": "invoke",
			"fileName": "DelegatingMethodAccessorImpl.java",
			"lineNumber": 43,
			"className": "jdk.internal.reflect.DelegatingMethodAccessorImpl",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": "java.base",
			"moduleVersion": "11.0.19",
			"methodName": "invoke",
			"fileName": "Method.java",
			"lineNumber": 566,
			"className": "java.lang.reflect.Method",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doInvoke",
			"fileName": "InvocableHandlerMethod.java",
			"lineNumber": 205,
			"className": "org.springframework.web.method.support.InvocableHandlerMethod",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "invokeForRequest",
			"fileName": "InvocableHandlerMethod.java",
			"lineNumber": 150,
			"className": "org.springframework.web.method.support.InvocableHandlerMethod",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "invokeAndHandle",
			"fileName": "ServletInvocableHandlerMethod.java",
			"lineNumber": 117,
			"className": "org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doResolveHandlerMethodException",
			"fileName": "ExceptionHandlerExceptionResolver.java",
			"lineNumber": 428,
			"className": "org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doResolveException",
			"fileName": "AbstractHandlerMethodExceptionResolver.java",
			"lineNumber": 75,
			"className": "org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "resolveException",
			"fileName": "AbstractHandlerExceptionResolver.java",
			"lineNumber": 142,
			"className": "org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "resolveException",
			"fileName": "HandlerExceptionResolverComposite.java",
			"lineNumber": 80,
			"className": "org.springframework.web.servlet.handler.HandlerExceptionResolverComposite",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "processHandlerException",
			"fileName": "DispatcherServlet.java",
			"lineNumber": 1331,
			"className": "org.springframework.web.servlet.DispatcherServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "processDispatchResult",
			"fileName": "DispatcherServlet.java",
			"lineNumber": 1142,
			"className": "org.springframework.web.servlet.DispatcherServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doDispatch",
			"fileName": "DispatcherServlet.java",
			"lineNumber": 1088,
			"className": "org.springframework.web.servlet.DispatcherServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doService",
			"fileName": "DispatcherServlet.java",
			"lineNumber": 964,
			"className": "org.springframework.web.servlet.DispatcherServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "processRequest",
			"fileName": "FrameworkServlet.java",
			"lineNumber": 1006,
			"className": "org.springframework.web.servlet.FrameworkServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doPost",
			"fileName": "FrameworkServlet.java",
			"lineNumber": 909,
			"className": "org.springframework.web.servlet.FrameworkServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "service",
			"fileName": "HttpServlet.java",
			"lineNumber": 696,
			"className": "javax.servlet.http.HttpServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "service",
			"fileName": "FrameworkServlet.java",
			"lineNumber": 883,
			"className": "org.springframework.web.servlet.FrameworkServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "service",
			"fileName": "HttpServlet.java",
			"lineNumber": 779,
			"className": "javax.servlet.http.HttpServlet",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "internalDoFilter",
			"fileName": "ApplicationFilterChain.java",
			"lineNumber": 227,
			"className": "org.apache.catalina.core.ApplicationFilterChain",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doFilter",
			"fileName": "ApplicationFilterChain.java",
			"lineNumber": 162,
			"className": "org.apache.catalina.core.ApplicationFilterChain",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doFilter",
			"fileName": "WsFilter.java",
			"lineNumber": 53,
			"className": "org.apache.tomcat.websocket.server.WsFilter",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "internalDoFilter",
			"fileName": "ApplicationFilterChain.java",
			"lineNumber": 189,
			"className": "org.apache.catalina.core.ApplicationFilterChain",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doFilter",
			"fileName": "ApplicationFilterChain.java",
			"lineNumber": 162,
			"className": "org.apache.catalina.core.ApplicationFilterChain",
			"nativeMethod": false
		},
		{
			"classLoaderName": null,
			"moduleName": null,
			"moduleVersion": null,
			"methodName": "doFilterInternal",
			"fileName": "RequestContextFilter.java",
			"lineNumber": 100,
			"className": "org.springframework.web.filter.RequestContextFilter",
			"nativeMethod": false
	 [...]

2023-05-03 02:55 UTC, EvgenyKoptubenko commented
Такой длинный стектрейс присылается на каждый ошибочный запрос. Лучше делать не так, а присылать пользователю идентификатор, который так же будут записываться в лог. По этому идентификатору можно в логах найти сообщение об ошибке

2023-05-03 02:57 UTC, EvgenyKoptubenko commented
Если есть желание, можно логирование в контроллерах убрать и воспользоваться https://www.baeldung.com/spring-http-logging

2023-05-03 03:03 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +            compilationEventRepository.deleteById(compEvent.getId());
Выполнять запросы к базе данных в цикле довольно плохая идея, т.к. каждый запрос занимает connection к базе данных, тратится лишнее время на открытие/закрытия подключения к базе данных.
Если есть желание, попробуй batch https://www.baeldung.com/spring-data-jpa-batch-inserts

2023-05-03 03:10 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/ewm/event/EventService.java
> +                    .collect(Collectors.toList());
точно ли collect меняет eventList, из которого взять стрим? Не нужно тут делать присвоение и использовать значение, которое выдает collect?

2023-05-03 03:10 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/ewm/participationReques/ParticipationRequestService.java
> +        ;
лишняя точка с запятой

2023-05-03 03:12 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложение по изменению обработки ошибок

2023-05-04 00:57 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Приступай к следующему заданию. Спасибо.

2023-05-04 09:09 UTC, merged